### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by itwysgsl** [cpuchain/ApiServer#1]
Hi there, just want to let you know that there is couple things you may need to change :)
- Reward calculation function [here](https://github.com/cpuchain/ApiServer/blob/master/core/utils.py#L21-L23) 
- Amount of satoshis [here](https://github.com/cpuchain/ApiServer/blob/master/core/utils.py#L25-L29) (MBC uses 4 by decault, but I think you need 8)
- Also, you don't need timestampindex and spentindex, addressindex should be enough

**Comment by itwysgsl** [comment]
Please check this https://github.com/cpuchain/ApiServer/commit/a206912ab682615c3ce33973615687b8043c71e6#commitcomment-35805081

**Comment by streetcrypto7** [comment]
I've fixed them all, thank you so much @itwysgsl , kudos to you 🎉

**Comment by itwysgsl** [comment]
You are welcome @streetcrypto7 \:)
